"""allow null token count before embedding

Revision ID: af1ec69b8625
Revises: 8a9e22681ab2
Create Date: 2026-09-13 16:44:52.387523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af1ec69b8625'
down_revision: Union[str, Sequence[str], None] = '8a9e22681ab2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document_chunks', 'token_count',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
