import { useEffect, useState } from 'react'
import { api, upload, type Citation, type Document, type Message, type User } from './api'

type Conversation = { id: string; title: string }

function SignIn({ onLogin }: { onLogin: (user: User) => void }) {
  const [email, setEmail] = useState(''), [password, setPassword] = useState(''), [error, setError] = useState(''), [busy, setBusy] = useState(false)
  const invite = new URLSearchParams(location.search).get('invite')
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setBusy(true); setError('')
    try { if (invite) { await api('/auth/accept', { method: 'POST', body: JSON.stringify({ token: invite, password }) }); history.replaceState(null, '', '/'); setError('Account created. Sign in with your email and password.') }
      else onLogin(await api<User>('/auth/login', { method: 'POST', body: JSON.stringify({ email, password }) })) }
    catch (err) { setError((err as Error).message) } finally { setBusy(false) }
  }
  return <main className="auth-wrap"><section className="auth-card"><div className="brand-mark">✳</div><span className="eyebrow">PRIVATE KNOWLEDGE WORKSPACE</span><h1>{invite ? 'Accept invitation' : 'Welcome back'}</h1><p>Find answers in your documents, with citations you can inspect.</p><form onSubmit={submit}>{!invite && <label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} autoComplete="username" required /></label>}<label>Password<input type="password" value={password} onChange={e => setPassword(e.target.value)} autoComplete={invite ? 'new-password' : 'current-password'} minLength={invite ? 12 : undefined} required /></label><button className="primary" disabled={busy}>{busy ? 'Please wait…' : invite ? 'Create account' : 'Sign in'}</button></form>{error && <p className="notice" role="alert">{error}</p>}</section></main>
}

function Documents({ user }: { user: User }) {
  const [documents, setDocuments] = useState<Document[]>([]), [error, setError] = useState(''), [progress, setProgress] = useState<number|null>(null)
  const refresh = () => api<Document[]>('/documents').then(setDocuments).catch(e => setError(e.message))
  useEffect(() => { refresh(); const timer = window.setInterval(refresh, 4000); return () => clearInterval(timer) }, [])
  async function onFile(file?: File) { if (!file) return; setError(''); setProgress(0); try { await upload(file, setProgress); await refresh() } catch(e) { setError((e as Error).message); await refresh() } finally { setProgress(null) } }
  async function remove(doc: Document) { if (!window.confirm(`Delete ${doc.original_filename}?`)) return; try { await api(`/documents/${doc.id}`, { method: 'DELETE' }); await refresh() } catch(e) { setError((e as Error).message) } }
  async function retry(doc: Document) { try { await api(`/documents/${doc.id}/process`, { method: 'POST' }); await refresh() } catch(e) { setError((e as Error).message) } }
  return <section><div className="section-head"><div><span className="eyebrow">LIBRARY</span><h2>Documents</h2><p>Upload text based PDFs to make them searchable. Processing continues in the background.</p></div>{user.role !== 'VIEWER' && <label className="upload-button">+ Upload PDF<input type="file" accept="application/pdf,.pdf" onChange={e => { onFile(e.target.files?.[0]); e.target.value = '' }} hidden /></label>}</div>{progress !== null && <div className="notice">Uploading: {progress}%<progress value={progress} max="100" /></div>}{error && <p className="notice error" role="alert">{error}</p>}<div className="panel list">{documents.length === 0 ? <div className="empty">No documents yet. Upload a PDF to begin.</div> : documents.map(doc => <div className="doc-row" key={doc.id}><div className="file-icon">PDF</div><div className="doc-title"><strong>{doc.original_filename}</strong><small>{(doc.file_size / 1024).toFixed(0)} KB · {new Date(doc.created_at).toLocaleDateString()}</small>{doc.status === 'failed' && <small className="error">{doc.error_message}</small>}</div><span className={'badge ' + doc.status}>{doc.status}</span>{user.role !== 'VIEWER' && <div className="actions">{doc.status === 'failed' && <button onClick={() => retry(doc)}>Retry</button>}<button aria-label={`Delete ${doc.original_filename}`} onClick={() => remove(doc)}>Delete</button></div>}</div>)}</div></section>
}

function Chat() {
  const [conversations, setConversations] = useState<Conversation[]>([]), [conversationId, setConversationId] = useState<string|null>(null), [messages, setMessages] = useState<Message[]>([]), [question, setQuestion] = useState(''), [busy, setBusy] = useState(false), [error, setError] = useState(''), [activeSource, setActiveSource] = useState<Citation|null>(null)
  const refresh = () => api<Conversation[]>('/chat/conversations').then(setConversations).catch(() => {})
  useEffect(() => { refresh() }, [])
  async function open(id: string) { try { const data = await api<{messages:Message[]}>(`/chat/conversations/${id}`); setMessages(data.messages); setConversationId(id); setError('') } catch(e) { setError((e as Error).message) } }
  async function ask(event: React.FormEvent) { event.preventDefault(); const text = question.trim(); if (!text || busy) return; setQuestion(''); setError(''); setBusy(true); setMessages(previous => [...previous, { role:'user', content:text, citations:[] }]); try { const data = await api<{answer:string;citations:Citation[];conversation_id:string}>('/chat/query', { method:'POST', body: JSON.stringify({ question:text, conversation_id:conversationId }) }); setConversationId(data.conversation_id); setMessages(previous => [...previous, { role:'assistant', content:data.answer, citations:data.citations }]); refresh() } catch(e) { setError((e as Error).message); setQuestion(text); setMessages(previous => previous.slice(0, -1)) } finally { setBusy(false) } }
  return <section className="chat-layout"><aside className="history"><button className="new-chat" onClick={() => { setConversationId(null); setMessages([]); setError('') }}>+ New conversation</button><span className="eyebrow">RECENT</span>{conversations.map(c => <button key={c.id} className={'history-item ' + (c.id === conversationId ? 'selected' : '')} onClick={() => open(c.id)}>{c.title}</button>)}</aside><div className="chat-main"><div className="section-head"><div><span className="eyebrow">ASK YOUR LIBRARY</span><h2>Ask a question</h2><p>Every answer is grounded in the documents you can access.</p></div></div><div className="messages">{messages.length === 0 && <div className="empty-chat"><div className="sparkle">✳</div><h3>What would you like to know?</h3><p>Ask about a policy, process, or detail in your uploaded documents.</p></div>}{messages.map((m, index) => <article className={'message ' + m.role} key={m.id || index}><div className="message-label">{m.role === 'assistant' ? 'Knowledge Desk' : 'You'}</div><p>{m.content}</p>{m.citations.length > 0 && <div className="sources"><strong>Sources</strong>{m.citations.map(c => <button key={c.source_id} onClick={() => setActiveSource(c)}>[{c.source_id.split('-')[1]}] {c.document_name}, page {c.page_number ?? '—'}</button>)}</div>}</article>)}{busy && <div className="thinking">Searching your documents…</div>}</div>{error && <p className="notice error" role="alert">{error}</p>}<form className="composer" onSubmit={ask}><label className="sr-only" htmlFor="question">Question</label><input id="question" value={question} onChange={e => setQuestion(e.target.value)} placeholder="Ask a question about your documents…" maxLength={2000}/><button className="primary" disabled={busy || question.trim().length < 3}>Ask →</button></form></div>{activeSource && <div className="modal-backdrop" onClick={() => setActiveSource(null)}><div className="modal" role="dialog" aria-modal="true" aria-label="Citation details" onClick={e => e.stopPropagation()}><button className="close" onClick={() => setActiveSource(null)} aria-label="Close">×</button><span className="eyebrow">{activeSource.source_id}</span><h3>{activeSource.document_name}</h3><p>Page {activeSource.page_number ?? '—'}{activeSource.section_title ? ` · ${activeSource.section_title}` : ''}</p><blockquote>{activeSource.excerpt}</blockquote></div></div>}</section>
}

function Team() {
  const [email, setEmail] = useState(''), [role, setRole] = useState('VIEWER'), [link, setLink] = useState(''), [users, setUsers] = useState<User[]>([]), [error, setError] = useState('')
  const [usage, setUsage] = useState<{model:string;operation:string;input_tokens:number;output_tokens:number}[]>([])
  useEffect(() => { api<User[]>('/auth/users').then(setUsers).catch(e => setError(e.message)); api<{models:typeof usage}>('/usage').then(data => setUsage(data.models)).catch(() => {}) }, [])
  async function invite(event: React.FormEvent) { event.preventDefault(); setError(''); setLink(''); try { const data = await api<{token:string}>('/auth/invitations', { method:'POST', body:JSON.stringify({email,role}) }); setLink(`${location.origin}/?invite=${encodeURIComponent(data.token)}`); setEmail('') } catch(e) { setError((e as Error).message) } }
  return <section><div className="section-head"><div><span className="eyebrow">WORKSPACE</span><h2>Team access</h2><p>Invite people into this workspace. Invitation links expire after 48 hours.</p></div></div><div className="panel team-panel"><form onSubmit={invite}><label>Email<input type="email" value={email} onChange={e => setEmail(e.target.value)} required /></label><label>Role<select value={role} onChange={e => setRole(e.target.value)}><option value="VIEWER">Viewer</option><option value="EDITOR">Editor</option><option value="ADMIN">Admin</option></select></label><button className="primary">Create invitation</button></form>{link && <div className="notice"><strong>Copy this one time link and send it securely:</strong><input readOnly value={link} onFocus={e => e.target.select()} /></div>}{error && <p className="notice error">{error}</p>}<h3>Members</h3>{users.map(u => <div className="member" key={u.id}><span>{u.email}</span><span className="badge">{u.role}</span></div>)}<h3>Model usage · last 30 days</h3>{usage.length === 0 ? <p>No model calls recorded yet.</p> : usage.map(row => <div className="member" key={row.model + row.operation}><span>{row.model} · {row.operation}</span><span>{row.input_tokens.toLocaleString()} in / {row.output_tokens.toLocaleString()} out</span></div>)}<p>Token counts are recorded; check your provider billing for current charges.</p></div></section>
}

export default function App() {
  const [user, setUser] = useState<User|null>(null), [loading, setLoading] = useState(true), [tab, setTab] = useState<'chat'|'documents'|'team'>('chat')
  useEffect(() => { api<User>('/auth/me').then(setUser).catch(() => {}).finally(() => setLoading(false)) }, [])
  if (loading) return <div className="loading">Loading workspace…</div>
  if (!user) return <SignIn onLogin={setUser} />
  return <div className="app-shell"><header><div className="logo"><span className="brand-mark">✳</span><span>Knowledge Desk</span></div><nav aria-label="Main navigation"><button className={tab === 'chat' ? 'active' : ''} onClick={() => setTab('chat')}>Ask</button><button className={tab === 'documents' ? 'active' : ''} onClick={() => setTab('documents')}>Documents</button>{user.role === 'ADMIN' && <button className={tab === 'team' ? 'active' : ''} onClick={() => setTab('team')}>Team</button>}</nav><div className="account"><span>{user.email}</span><button onClick={() => api('/auth/logout', { method:'POST' }).finally(() => setUser(null))}>Sign out</button></div></header><main>{tab === 'chat' ? <Chat /> : tab === 'documents' ? <Documents user={user} /> : <Team />}</main></div>
}
